# Name as cli to avoid name collision with the "aoc" directory.
binary := "cli"

default:
    @just --list

test:
    go test ./...

run:
    go run ./cmd/aoc

build:
    go build -o {{ binary }} ./cmd/aoc

benchmark: build
    hyperfine --time-unit microsecond --warmup 3 -N ./{{ binary }}
    time -v ./{{ binary }}

fmt:
    go fmt ./...

lint:
    golangci-lint run

clean:
    rm -f {{ binary }}
