default:
    @just --list

test:
    lake test

run:
    lake exe aoc

build:
    lake build

benchmark *args: build
    hyperfine --warmup 3 -N .lake/build/bin/aoc {{args}}
    time -v .lake/build/bin/aoc

clean:
    rm -rf .lake
