default:
    @just --list

test:
    odin test src/aoc

run:
    odin run src

build:
    odin build src -out:aoc

lint:
    odin check src -vet -strict-style

fmt:
    odinfmt -w src

benchmark *args: build
    hyperfine --warmup 3 -N ./aoc {{args}}
    time -v ./aoc

clean:
    rm -f ./aoc
