default:
    @just --list

test:
    scala-cli test .

run:
    scala-cli run .

build:
    scala-cli --power package . --assembly --force -o aoc

fmt:
    scalafmt .

benchmark *args: build
    hyperfine --warmup 3 -N ./aoc {{args}}
    time -v ./aoc

clean:
    rm -rf .scala-build aoc
