default:
    @just --list

test:
    scala-cli test -rewrite -indent .

run:
    scala-cli run -rewrite -indent .

build:
    scala-cli --power package . --assembly --force -o aoc

fmt:
    scalafmt .

benchmark: build
    hyperfine --warmup 3 -N ./aoc
    time -v ./aoc

clean:
    rm -rf .scala-build aoc
