default:
    @just --list

test:
    deno test

check:
    deno check src/main.ts

run:
    deno run --allow-read=input.txt src/main.ts

build:
    deno compile --allow-read=input.txt --output aoc src/main.ts

fmt:
    deno fmt

lint:
    deno lint

outdated:
    deno outdated

update:
    deno outdated --update

benchmark *args: build
    hyperfine --warmup 3 -N ./aoc {{args}}
    time -v ./aoc

clean:
    rm -f aoc
