default:
    @just --list

test:
    gleam test

run:
    gleam run

build:
    gleam export erlang-shipment

fmt:
    gleam format

benchmark: build
    hyperfine --warmup 3 -N "./build/erlang-shipment/entrypoint.sh run"
    time -v ./build/erlang-shipment/entrypoint.sh run

clean:
    rm -f build
