default:
    @just --list

test:
    gleam test

run:
    gleam run

build:
    gleam export erlang-shipment

fmt:
    gleam format

outdated:
    gleam deps outdated

update:
    gleam deps update

benchmark *args: build
    hyperfine --warmup 3 "./build/erlang-shipment/entrypoint.sh run" {{args}}
    time -v ./build/erlang-shipment/entrypoint.sh run

clean:
    rm -rf build
