java-options := "-XX:TieredStopAtLevel=1 -XX:+UseSerialGC -XX:SharedArchiveFile=target/aoc.jsa"

default:
    @just --list

test:
    clojure -X:test

run:
    clojure -M -m aoc

build:
    clojure -T:build uber
    java -XX:ArchiveClassesAtExit=target/aoc.jsa -cp target/aoc.jar clojure.main -e "(require 'aoc)" > /dev/null

fmt:
    cljfmt fix src test build.clj

lint:
    clj-kondo --lint src test build.clj

benchmark: build
    hyperfine --warmup 3 -N "java {{java-options}} -jar target/aoc.jar"
    time -v java {{java-options}} -jar target/aoc.jar

clean:
    rm -rf target .cpcache
