default:
    @just --list

test:
    zig build test

test-watch:
    zig build --watch test

run:
    zig build run

build:
    zig build --release=fast

fmt:
    zig fmt .

benchmark *args: build
    hyperfine --warmup 3 -N ./zig-out/bin/aoc {{args}}
    time -v ./zig-out/bin/aoc

clean:
    rm -rf zig-out/
