default:
    @just --list

test:
    cargo test

run:
    cargo run

build:
    cargo build --release

fmt:
    cargo fmt

lint:
    cargo clippy --all-targets -- -D warnings

outdated:
    cargo update --dry-run

update:
    cargo update

benchmark: build
    hyperfine --warmup 3 -N ./target/release/aoc
    time -v ./target/release/aoc

clean:
    cargo clean
