default:
    @just --list

test:
    pytest

run:
    python main.py

lint:
    ruff check

fmt:
    ruff format

outdated:
    uv pip compile --quiet --upgrade --group dev --no-header pyproject.toml

benchmark:
    hyperfine --warmup 3 -N "python main.py"
    time -v python main.py
