default:
    @just --list

test:
    mix test

build:
    mix escript.build

run: build
    ./aoc

outdated:
    mix hex.outdated

update:
    mix deps.update --all

benchmark: build
    hyperfine --warmup 3 -N ./aoc
    time -v ./aoc

fmt:
    mix format

clean:
    mix clean
