default:
    @just --list

build:
    dune build

run:
    dune exec aoc

run-watch:
    dune exec aoc -w

test:
    dune runtest

test-watch:
    dune runtest -w

fmt:
    dune build @fmt --auto-promote

benchmark: build
    hyperfine --warmup 3 -N ./_build/default/bin/main.exe
    time -v ./_build/default/bin/main.exe

clean:
    dune clean
